### ISSUE TITLE
write a simple javascript program

### ISSUE THREAD

**Issue by MasterIfeanyi** [MasterIfeanyi/Guessing-game#1]
Please create a "Guessing game" program using Node.js

Please follow the [Readme](https://github.com/MasterIfeanyi/Guessing-game/edit/main/Readme.md) for more details.

**Comment by spike-spiegel-21** [comment]
Hey, I will be working on this game. Please tell me whether we want to do this as a simple functional approach or some object-oriented?

**Comment by KanjiZain** [comment]
On It!

**Comment by MasterIfeanyi** [comment]
@spike-spiegel-21 Functional approach, please follow the readme for more information
